title: "Francesco Caporali"
url: "https://caporali.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
description: "Ph.D. student at Princeton ORFE"
profile_picture: "/files/images/profile_pic_caporali.jpg"
# favicon: true
# favicon_location: "/files/images/princeton_logo.png"
footer: true
footer_url: "https://github.com/ankitsultana/researcher"
sass:
  style: compressed
  sass_dir: _sass
nav:
  - name: "Main"
    link: "/"
  - name: "Resume"
    link: "/files/cv/cv_caporali.pdf"
  # - name: "Flashcards"
  #   link: "/flashcards"
  - name: "Surface"
    link: "/surface"
